from typing import List, Dict

# ────────────────────────  feed sources  ────────────────────────── #
FEED_SOURCES: List[Dict[str, str]] = [
    {"name": "TechCrunch",                "url": "https://techcrunch.com/feed/",                          "category": "tech"},
    {"name": "The Verge",                 "url": "https://www.theverge.com/rss/tech/index.xml",          "category": "tech"},
    {"name": "Ars Technica",              "url": "http://feeds.arstechnica.com/arstechnica/index",       "category": "tech"},
    {"name": "KDnuggets",                 "url": "https://www.kdnuggets.com/feed",                       "category": "data_science"},
    {"name": "Data Science Central",      "url": "https://www.datasciencecentral.com/feed/",             "category": "data_science"},
    {"name": "Machine Learning Mastery",  "url": "https://machinelearningmastery.com/feed/",            "category": "data_science"},
    {"name": "arXiv cs.LG",               "url": "https://arxiv.org/rss/cs.LG",                          "category": "data_science"},
    {"name": "arXiv stat.ML",             "url": "https://arxiv.org/rss/stat.ML",                        "category": "data_science"},
    {"name": "OpenAI News",               "url": "https://openai.com/news/rss.xml",                      "category": "llm_tools"},
    {"name": "Hugging Face Blog",         "url": "https://huggingface.co/blog/rss.xml",                  "category": "llm_tools"},
    {"name": "Google AI Blog",            "url": "https://ai.googleblog.com/atom.xml",                   "category": "llm_tools"},
    {"name": "The Hacker News",           "url": "https://feeds.feedburner.com/TheHackersNews",          "category": "cybersecurity"},
    {"name": "Krebs on Security",         "url": "https://krebsonsecurity.com/feed/",                    "category": "cybersecurity"},
    {"name": "Schneier on Security",      "url": "https://www.schneier.com/blog/atom.xml",               "category": "cybersecurity"},
    {"name": "Phoronix",                  "url": "https://www.phoronix.com/rss.php",                     "category": "linux"},
    {"name": "LWN.net",                   "url": "https://lwn.net/headlines/rss",                        "category": "linux"},
    {"name": "ServeTheHome",              "url": "https://www.servethehome.com/feed/",                   "category": "linux"},
    {"name": "The Audio Programmer",      "url": "https://theaudioprogrammer.com/rss/",                  "category": "audio_dsp"},
    {"name": "Designing Sound",           "url": "https://designingsound.org/feed/",                     "category": "audio_dsp"},
    {"name": "KVR Audio",                 "url": "https://www.kvraudio.com/xml/rss.xml",                 "category": "audio_dsp"},
    {"name": "VentureBeat",               "url": "https://venturebeat.com/feed/",                        "category": "startups"},
    {"name": "First Round Review",        "url": "https://review.firstround.com/rss",                    "category": "startups"},
    # General news sources
    {"name": "Reuters",                   "url": "https://feeds.reuters.com/reuters/topNews",            "category": "news"},
    {"name": "Associated Press",          "url": "https://apnews.com/apf-topnews?format=xml",            "category": "news"},
    {"name": "NPR",                       "url": "https://www.npr.org/rss/rss.php?id=1001",             "category": "news"},
    {"name": "PBS NewsHour",              "url": "https://www.pbs.org/newshour/rss.xml",                "category": "news"},
    {"name": "CBS News",                  "url": "https://www.cbsnews.com/latest/rss/main",             "category": "news"},
    {"name": "The New York Times",        "url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", "category": "news"},
    {"name": "The Washington Post",       "url": "https://feeds.washingtonpost.com/rss/homepage",       "category": "news"},
    {"name": "The Wall Street Journal",   "url": "https://www.wsj.com/xml/rss/3_7014.xml",               "category": "news"},
    {"name": "BBC News",                  "url": "http://feeds.bbci.co.uk/news/rss.xml",                "category": "news"},
    {"name": "The Guardian",              "url": "https://www.theguardian.com/world/rss",               "category": "news"},
    {"name": "Financial Times",           "url": "https://www.ft.com/?format=rss",                      "category": "news"},
    {"name": "Bloomberg",                 "url": "https://www.bloomberg.com/feed/podcast/etf-report.xml?via=rss", "category": "news"},
    {"name": "Al Jazeera English",        "url": "https://www.aljazeera.com/xml/rss/all.xml",            "category": "news"},
    {"name": "Deutsche Welle",            "url": "https://rss.dw.com/rdf/rss-en-all",                    "category": "news"},
    {"name": "NHK World – Japan",         "url": "https://www3.nhk.or.jp/rss/news/cat0.xml",             "category": "news"},
    {"name": "Christian Science Monitor", "url": "https://rss.csmonitor.com/feeds/all",                  "category": "news"},
    {"name": "ProPublica",                "url": "https://www.propublica.org/feeds/propublica.rss",      "category": "news"},
    {"name": "CBC News",                  "url": "http://rss.cbc.ca/lineup/topstories.xml",             "category": "news"},
    {"name": "South China Morning Post",  "url": "https://www.scmp.com/rss",                            "category": "news"},
    {"name": "Voice of America",          "url": "https://www.voanews.com/rssfeeds",                    "category": "news"},
]

# Additional reputable sources (20 entries)
FEED_SOURCES.extend([
    {"name": "Scientific American",             "url": "https://www.scientificamerican.com/feed/",                   "category": "science"},
    {"name": "Nature",                          "url": "https://www.nature.com/nature.rss",                         "category": "science"},
    {"name": "Science Magazine",                "url": "https://www.sciencemag.org/rss/news_current.xml",           "category": "science"},
    {"name": "PNAS",                            "url": "https://www.pnas.org/rss/current.xml",                      "category": "science"},
    {"name": "ScienceDaily",                    "url": "https://www.sciencedaily.com/rss/all.xml",                  "category": "science"},
    {"name": "New Scientist",                   "url": "https://www.newscientist.com/feed/home/",                  "category": "science"},
    {"name": "Phys.org",                        "url": "https://phys.org/rss-feed/",                                "category": "science"},
    {"name": "Live Science",                    "url": "https://www.livescience.com/feeds/all",                     "category": "science"},
    {"name": "The Scientist",                   "url": "https://www.the-scientist.com/feed/rss",                    "category": "science"},
    {"name": "EurekAlert!",                     "url": "https://www.eurekalert.org/rss.xml",                        "category": "science"},
    {"name": "Smithsonian (Science & Nature)",  "url": "https://www.smithsonianmag.com/rss/science-nature/",        "category": "science"},
    {"name": "IFLScience",                      "url": "https://www.iflscience.com/rss",                            "category": "science"},
    {"name": "Undark Magazine",                 "url": "https://undark.org/feed/",                                  "category": "science"},
    {"name": "Stories in Science",              "url": "https://storiesinscience.org/feed/",                        "category": "science"},
    {"name": "Starts With A Bang!",             "url": "https://medium.com/feed/starts-with-a-bang",                "category": "science"},
    {"name": "Pew Research Center",             "url": "https://www.pewresearch.org/rss/",                          "category": "research"},
    {"name": "Brookings Institution",           "url": "https://www.brookings.edu/feed/",                           "category": "policy"},
    {"name": "Council on Foreign Relations",    "url": "https://www.cfr.org/rss/all.xml",                           "category": "policy"},
    {"name": "RAND Corporation",                "url": "https://www.rand.org/rss.xml",                              "category": "policy"},
    {"name": "UN News",                         "url": "https://www.un.org/apps/news/rss/rss.xml",                  "category": "policy"},
])

FEED_SOURCES.extend([
    {"name": "C-SPAN",                                 "url": "https://www.c-span.org/rss/",                            "category": "news"},
    {"name": "The Economist (World News)", "url": "https://www.economist.com/international/rss.xml", "category": "news"},
    {"name": "The Economist (Science & Technology)", "url": "https://www.economist.com/science-and-technology/rss.xml", "category": "tech"},
    {"name": "The Economist (Business)", "url": "https://www.economist.com/business/rss.xml", "category": "business"},
    {"name": "The Economist (Finance & Economics)", "url": "https://www.economist.com/finance-and-economics/rss.xml", "category": "business"},
    {"name": "The Economist (Politics - Leaders)", "url": "https://www.economist.com/leaders/rss.xml", "category": "policy"},
    {"name": "The Economist (Climate Change)", "url": "https://www.economist.com/climate-change/rss.xml", "category": "science"},
    {"name": "The Economist (United States)", "url": "https://www.economist.com/united-states/rss.xml", "category": "news"},
    {"name": "The Economist (Technology Quarterly)", "url": "https://www.economist.com/technology-quarterly/rss.xml", "category": "tech"},
    {"name": "The Economist (The World Ahead)", "url": "https://www.economist.com/the-world-ahead/rss.xml", "category": "news"},
    {"name": "The Bureau of Investigative Journalism", "url": "https://www.thebureauinvestigates.com/feed/atom",        "category": "news"},
    {"name": "USA Today",                              "url": "https://rssfeeds.usatoday.com/UsatodaycomNation-TopStories", "category": "news"},
    {"name": "Forbes",                                 "url": "https://www.forbes.com/business/feed/",                "category": "news"},
    {"name": "UPI",                                    "url": "https://www.upi.com/rss/news/top_news/",                 "category": "news"},
    {"name": "Le Monde",                               "url": "https://www.lemonde.fr/en/rss/une.xml",                  "category": "news"},
    {"name": "Euronews",                               "url": "https://www.euronews.com/rss",                           "category": "news"},
    {"name": "Time Magazine",                          "url": "https://time.com/feed/",                                 "category": "news"}
])

FEED_SOURCES.extend([
    {"name": "We Want Science",              "url": "https://www.wewantscience.com/feed",                  "category": "science"},
    {"name": "WIRED Science",                "url": "https://www.wired.com/category/science/feed",         "category": "science"},
    {"name": "ZME Science",                  "url": "https://www.zmescience.com/feed/",                    "category": "science"},
    {"name": "Darknet Diaries",              "url": "https://feeds.megaphone.fm/darknetdiaries",                 "category": "cybersecurity"},
    {"name": "Graham Cluley",                "url": "https://grahamcluley.com/feed/",                      "category": "cybersecurity"},
    {"name": "SANS Internet Storm Center",   "url": "https://isc.sans.edu/rssfeed_full.xml",               "category": "cybersecurity"},
    {"name": "Securelist",                   "url": "https://securelist.com/feed/",                        "category": "cybersecurity"},
    {"name": "Troy Hunt",                    "url": "https://www.troyhunt.com/rss/",                       "category": "cybersecurity"},
    {"name": "WeLiveSecurity",               "url": "https://feeds.feedburner.com/eset/blog",              "category": "cybersecurity"},
    {"name": "Public Knowledge News",        "url": "https://publicknowledge.org/feed",                    "category": "policy"},
    {"name": "Dataconomy",                   "url": "https://dataconomy.com/feed",                         "category": "data_science"}
])

FEED_SOURCES.extend([
    {"name": "MacRumors",                      "url": "https://feeds.macrumors.com/MacRumors-All",       "category": "tech"},
    {"name": "9to5Mac",                        "url": "https://9to5mac.com/feed",                        "category": "tech"},
    {"name": "AppleInsider",                   "url": "https://appleinsider.com/rss/news",               "category": "tech"},
    {"name": "Gadgets Beat",                   "url": "https://gadgetsbeat.com/feed/",                   "category": "tech"},
    {"name": "Slashdot",                       "url": "http://rss.slashdot.org/Slashdot/slashdot",       "category": "tech"},
    {"name": "BAIR Blog",                      "url": "https://bair.berkeley.edu/blog/feed.xml",         "category": "data_science"},
    {"name": "Towards Data Science",           "url": "https://towardsdatascience.com/feed",             "category": "data_science"},
    {"name": "DeepMind Blog",                  "url": "https://deepmind.com/blog/feed/basic/",           "category": "llm_tools"},
    {"name": "LinuxJournal",                   "url": "https://www.linuxjournal.com/node/feed",          "category": "linux"},
    {"name": "LinuxToday",                     "url": "https://www.linuxtoday.com/feed/",                "category": "linux"},
    {"name": "LinuxInsider",                   "url": "https://linuxinsider.com/feed/",                  "category": "linux"},
    {"name": "HowToForge",                     "url": "https://www.howtoforge.com/feed.rss",             "category": "linux"},
    {"name": "Rocky Linux RSS",                "url": "https://rockylinux.org/rss.xml",                  "category": "linux"},
    {"name": "Latest Hacking News",            "url": "https://latesthackingnews.com/feed/",             "category": "cybersecurity"},
    {"name": "KitPloit",                       "url": "https://www.kitploit.com/feeds/posts/default",    "category": "cybersecurity"},
    {"name": "Microsoft Security Blog",        "url": "https://api.msrc.microsoft.com/update-guide/rss", "category": "cybersecurity"},
    {"name": "Fox Business",                   "url": "https://moxie.foxbusiness.com/google-publisher/latest.xml", "category": "business_tech"}
])

FEED_SOURCES.extend([
    {"name": "Los Angeles Times",             "url": "https://feeds.latimes.com/latimes/news",                                               "category": "news"},
    {"name": "Chicago Tribune",               "url": "https://www.chicagotribune.com/arcio/rss/category/news/?outputType=xml",              "category": "news"},
    {"name": "Houston Chronicle",             "url": "https://www.chron.com/rss/",                                                          "category": "news"},
    {"name": "Miami Herald",                  "url": "https://www.miamiherald.com/news/?outputType=rss",                                    "category": "news"},
    {"name": "WCVB Boston",                   "url": "https://www.wcvb.com/topstories-rss",                                                 "category": "news"},
    {"name": "Seattle Times",                 "url": "https://www.seattletimes.com/feed/",                                                  "category": "news"},
    {"name": "San Francisco Chronicle",       "url": "https://www.sfchronicle.com/rss",                                                    "category": "news"},
    {"name": "Denver Post",                   "url": "https://www.denverpost.com/feed/",                                                    "category": "news"},
    {"name": "Dallas Morning News",           "url": "https://www.dallasnews.com/news/?outputType=rss",                                     "category": "news"},
    {"name": "Atlanta Journal-Constitution",  "url": "https://www.ajc.com/news/rss/",                                                      "category": "news"},
    {"name": "Philadelphia Inquirer",         "url": "https://www.inquirer.com/arcio/rss/category/news/?outputType=xml",                    "category": "news"},
    {"name": "Detroit Free Press",            "url": "https://rssfeeds.freep.com/freep/home",                                               "category": "news"},
    {"name": "Star Tribune (Minneapolis)",    "url": "https://www.startribune.com/rss/",                                                    "category": "news"},
    {"name": "Tampa Bay Times",               "url": "https://www.tampabay.com/news/?outputType=rss",                                       "category": "news"},
    {"name": "Orlando Sentinel",              "url": "https://www.orlandosentinel.com/news/?outputType=rss",                                "category": "news"},
    {"name": "Baltimore Sun",                 "url": "https://www.baltimoresun.com/arcio/rss/category/news/?outputType=xml",                "category": "news"},
    {"name": "Pittsburgh Post-Gazette",       "url": "https://www.post-gazette.com/rss/news",                                              "category": "news"},
    {"name": "Cleveland Plain Dealer",        "url": "https://www.cleveland.com/arcio/rss/category/news/?outputType=xml",                   "category": "news"},
    {"name": "Times-Picayune / NOLA.com",     "url": "https://www.nola.com/news/?outputType=rss",                                           "category": "news"},
    {"name": "Kansas City Star",              "url": "https://www.kansascity.com/news/?outputType=rss",                                     "category": "news"},
    {"name": "St. Louis Post-Dispatch",       "url": "https://www.stltoday.com/news/?outputType=rss",                                       "category": "news"},
    {"name": "Milwaukee Journal Sentinel",    "url": "https://www.jsonline.com/news/?outputType=rss",                                       "category": "news"},
    {"name": "Indianapolis Star",             "url": "https://www.indystar.com/news/?outputType=rss",                                       "category": "news"},
    {"name": "Las Vegas Review-Journal",      "url": "https://www.reviewjournal.com/feed/",                                                "category": "news"},
    {"name": "San Diego Union-Tribune",       "url": "https://www.sandiegouniontribune.com/rss",                                            "category": "news"},
    {"name": "Salt Lake Tribune",             "url": "https://www.sltrib.com/news/rss/",                                                    "category": "news"},
    {"name": "The Oregonian",                 "url": "https://www.oregonlive.com/news/rss",                                                 "category": "news"},
    {"name": "Charlotte Observer",            "url": "https://www.charlotteobserver.com/news/?outputType=rss",                              "category": "news"},
    {"name": "News & Observer (Raleigh)",     "url": "https://www.newsobserver.com/news/?outputType=rss",                                   "category": "news"},
    {"name": "The Tennessean",                "url": "https://www.tennessean.com/news/?outputType=rss",                                     "category": "news"},
    {"name": "Arizona Republic",              "url": "https://rssfeeds.azcentral.com/arizona/home",                                         "category": "news"},
    {"name": "Austin American-Statesman",     "url": "https://www.statesman.com/news/?outputType=rss",                                      "category": "news"},
    {"name": "Columbus Dispatch",             "url": "https://www.dispatch.com/news/rss/",                                                  "category": "news"},
    {"name": "Richmond Times-Dispatch",       "url": "https://richmond.com/search/?f=rss&t=article&c=news_local",                           "category": "news"},
    {"name": "Providence Journal",            "url": "https://www.providencejournal.com/news?template=rss&mime=xml",                        "category": "news"},
    {"name": "Star-Ledger (NJ.com)",          "url": "https://www.nj.com/news/?outputType=rss",                                             "category": "news"},
    {"name": "Omaha World-Herald",            "url": "https://omaha.com/search/?f=rss&t=article&c=news_local",                              "category": "news"},
    {"name": "Honolulu Star-Advertiser",      "url": "https://www.staradvertiser.com/category/breaking-news/feed/",                         "category": "news"},
    {"name": "Anchorage Daily News",          "url": "https://www.adn.com/feed/",                                                           "category": "news"},
    {"name": "The Independent (UK)",          "url": "https://www.independent.co.uk/news/world/rss",                                        "category": "news"},
    {"name": "The Telegraph (UK)",            "url": "https://www.telegraph.co.uk/news/rss.xml",                                            "category": "news"},
    {"name": "Sky News (World)",              "url": "https://feeds.skynews.com/feeds/rss/world.xml",                                       "category": "news"},
    {"name": "RTÉ News (Ireland)",            "url": "https://www.rte.ie/rss/news/headlines.xml",                                           "category": "news"},
    {"name": "The Irish Times",               "url": "https://www.irishtimes.com/news/rss",                                                "category": "news"},
    {"name": "The Scotsman",                  "url": "https://www.scotsman.com/news/rss",                                                   "category": "news"},
    {"name": "Le Figaro",                     "url": "https://www.lefigaro.fr/rss/figaro_actualites.xml",                                   "category": "news"},
    {"name": "Libération",                    "url": "https://www.liberation.fr/rss/",                                                      "category": "news"},
    {"name": "Der Spiegel (Int.)",            "url": "https://www.spiegel.de/international/index.rss",                                      "category": "news"},
    {"name": "Die Zeit",                      "url": "https://www.zeit.de/index.rss",                                                      "category": "news"},
    {"name": "Frankfurter Allgemeine",        "url": "https://www.faz.net/rss/aktuell/",                                                    "category": "news"},
    {"name": "El País (Int.)",                "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/international",      "category": "news"},
    {"name": "El Mundo",                      "url": "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",                                 "category": "news"},
    {"name": "ABC España",                    "url": "https://www.abc.es/rss/feeds/abcPortada.xml",                                         "category": "news"},
    {"name": "Corriere della Sera",           "url": "https://rss.corriere.it/rss/homepage.xml",                                            "category": "news"},
    {"name": "La Repubblica",                 "url": "https://www.repubblica.it/rss/homepage/rss2.0.xml",                                   "category": "news"},
    {"name": "Il Sole 24 Ore",                "url": "https://www.ilsole24ore.com/arc/outboundfeeds/rss/?outputType=xml",                   "category": "business"},
    {"name": "Politico Europe",               "url": "https://www.politico.eu/feed/",                                                       "category": "news"},
    {"name": "Euractiv",                      "url": "https://www.euractiv.com/feed/",                                                      "category": "news"},
    {"name": "SwissInfo",                     "url": "https://www.swissinfo.ch/service/swissinfo/rss/eng/rss.xml",                          "category": "news"},
    {"name": "Le Soir",                       "url": "https://www.lesoir.be/rss/general.xml",                                               "category": "news"},
    {"name": "NOS (Netherlands)",             "url": "https://feeds.nos.nl/nosnieuwsalgemeen",                                              "category": "news"},
    {"name": "Yle (Finland)",                 "url": "https://feeds.yle.fi/uutiset/v1/recent-news.rss?publisherIds=YLE_UUTISET",            "category": "news"},
    {"name": "NRK (Norway)",                  "url": "https://www.nrk.no/toppsaker.rss",                                                    "category": "news"},
    {"name": "DR (Denmark)",                  "url": "https://www.dr.dk/nyheder/service/feeds/allenyheder",                                 "category": "news"},
    {"name": "Svenska Dagbladet",             "url": "https://www.svd.se/?service=rss",                                                     "category": "news"},
    {"name": "Dagens Nyheter",                "url": "https://www.dn.se/rss",                                                               "category": "news"},
    {"name": "Aftenposten",                   "url": "https://www.aftenposten.no/rss",                                                      "category": "news"},
    {"name": "Helsingin Sanomat",             "url": "https://www.hs.fi/rss/tuoreimmat.xml",                                                "category": "news"},
    {"name": "The Hindu",                     "url": "https://www.thehindu.com/news/feeder/default.rss",                                    "category": "news"},
    {"name": "Times of India",                "url": "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",                        "category": "news"},
    {"name": "Hindustan Times",               "url": "https://www.hindustantimes.com/rss/topnews/rssfeed.xml",                              "category": "news"},
    {"name": "Indian Express",                "url": "https://indianexpress.com/section/india/feed/",                                       "category": "news"},
    {"name": "Nikkei Asia",                   "url": "https://asia.nikkei.com/rss/feed/nar",                                                "category": "news"},
    {"name": "The Japan Times",               "url": "https://www.japantimes.co.jp/feed/",                                                  "category": "news"},
    {"name": "Asahi Shimbun",                 "url": "https://www.asahi.com/rss/asahi/newsheadlines.rdf",                                   "category": "news"},
    {"name": "Yomiuri Shimbun",               "url": "https://www.yomiuri.co.jp/rss/yol/topstories",                                        "category": "news"},
    {"name": "Korea Herald",                  "url": "https://www.koreaherald.com/rss",                                                     "category": "news"},
    {"name": "Korea JoongAng Daily",          "url": "https://koreajoongangdaily.joins.com/rss/news",                                       "category": "news"},
    {"name": "The Straits Times",             "url": "https://www.straitstimes.com/news/world/rss.xml",                                     "category": "news"},
    {"name": "Channel NewsAsia",              "url": "https://www.channelnewsasia.com/rssfeeds/8395986",                                    "category": "news"},
    {"name": "Jakarta Post",                  "url": "https://www.thejakartapost.com/rss",                                                  "category": "news"},
    {"name": "Bangkok Post",                  "url": "https://www.bangkokpost.com/rss/data/news.xml",                                       "category": "news"},
    {"name": "The Nation (Thailand)",         "url": "https://www.nationthailand.com/rss/national",                                         "category": "news"},
    {"name": "Manila Bulletin",               "url": "https://mb.com.ph/feed/",                                                             "category": "news"},
    {"name": "Rappler (Philippines)",         "url": "https://www.rappler.com/feed/",                                                       "category": "news"},
    {"name": "Dawn (Pakistan)",               "url": "https://www.dawn.com/feeds/home",                                                     "category": "news"},
    {"name": "Express Tribune",               "url": "https://tribune.com.pk/feed/",                                                        "category": "news"},
    {"name": "The Daily Star (Bangladesh)",   "url": "https://www.thedailystar.net/frontpage/rss.xml",                                      "category": "news"},
    {"name": "Taipei Times",                  "url": "https://www.taipeitimes.com/rss/index",                                               "category": "news"},
    {"name": "Arab News",                     "url": "https://www.arabnews.com/cat/rssxml",                                                 "category": "news"},
    {"name": "Haaretz",                       "url": "https://www.haaretz.com/rss",                                                         "category": "news"},
    {"name": "The Times of Israel",           "url": "https://www.timesofisrael.com/feed/",                                                 "category": "news"},
    {"name": "Mail & Guardian",               "url": "https://mg.co.za/feed/",                                                              "category": "news"},
    {"name": "News24 (South Africa)",         "url": "https://feeds.news24.com/articles/News24/TopStories/rss",                             "category": "news"},
    {"name": "Daily Nation (Kenya)",          "url": "https://nation.africa/ke/rss",                                                        "category": "news"},
    {"name": "The Guardian Nigeria",          "url": "https://guardian.ng/feed/",                                                           "category": "news"},
    {"name": "The East African",              "url": "https://www.theeastafrican.co.ke/tea/rss",                                            "category": "news"},
    {"name": "Clarín (Argentina)",            "url": "https://www.clarin.com/rss/lo-ultimo/",                                               "category": "news"},
    {"name": "La Nación (Argentina)",         "url": "https://www.lanacion.com.ar/rss/lo-ultimo/",                                          "category": "news"},
    {"name": "El Universal (Mexico)",         "url": "https://www.eluniversal.com.mx/rss/",                                                 "category": "news"}
])